<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>netstandard2.1</TargetFramework>
	<Nullable>enable</Nullable>
	<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".ClientSdk.ProtobufNet", ""))</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<!--
		  Pull in every .cs under SharedWithServer/, excluding nothing.
		  The <Link> makes them appear in a virtual SharedCode folder in VS.
		-->
		<Compile Include="..\Orpius.Platform.ClientSdk.ProtobufNet.SharedWithServer\**\*.cs">
			<Link>SharedWithServer\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Compile>
		<Compile Remove="..\Orpius.Platform.ClientSdk.ProtobufNet.SharedWithServer\obj\**" />
	</ItemGroup>

  <ItemGroup>
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform.Shared\Inferencing\RpcMessages\ConversationMessages.cs" Link="Inferencing\ConversationMessages.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform.Shared\OperationsModel\RpcOperationsService\ChatRequest.cs" Link="OperationsModel\RpcOperationsService\ChatRequest.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform.Shared\OperationsModel\RpcOperationsService\OperationHeaders.cs" Link="RpcServices\OperationHeaders.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform.Shared\ToolsModel\RpcToolsRegistrationService\ToolsRegistrationHeaders.cs" Link="RpcServices\ToolsRegistrationHeaders.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform\OperationsModel\RpcOperationsService\IOperationsService.cs" Link="RpcServices\IOperationsService.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform\ToolsModel\RpcToolProviderService\IToolProviderService.cs" Link="RpcServices\IToolProviderService.cs" />
	<Compile Include="..\..\..\..\Platform\PlatformRepo\Source\Orpius.Platform\ToolsModel\RpcToolsRegistrationService\IToolsRegistrationService.cs" Link="RpcServices\IToolsRegistrationService.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Google.Protobuf" Version="3.31.0" />
	<PackageReference Include="protobuf-net.Grpc" Version="1.2.2" />
	<PackageReference Include="System.Text.Json" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
	<Folder Include="CopiedFrom\Platform.Server\" />
	<Folder Include="CopiedFrom\Platform\" />
	<Folder Include="Inferencing\" />
	<Folder Include="OperationsModel\RpcOperationsService\" />
	<Folder Include="RpcServices\" />
  </ItemGroup>

</Project>
