<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".ClientSdk.ProtobufNet", ""))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<!--
		  Pull in every .cs under SharedWithServer/, excluding nothing.
		  The <Link> makes them appear in a virtual SharedCode folder in VS.
		-->
		<Compile Include="..\Orpius.Platform.ClientSdk.ProtobufNet.SharedWithServer\**\*.cs">
			<Link>SharedWithServer\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Compile>
		<Compile Remove="..\Orpius.Platform.ClientSdk.ProtobufNet.SharedWithServer\obj\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.32.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
		<PackageReference Include="protobuf-net.Grpc" Version="1.2.2" />
		<PackageReference Include="protobuf-net.Grpc.ClientFactory" Version="1.2.2" />
		<PackageReference Include="System.Text.Json" Version="9.0.8" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="CopiedFrom\Platform.Server\" />
		<Folder Include="CopiedFrom\Platform\" />
		<Folder Include="RpcServices\" />
	</ItemGroup>

	<!-- NuGet -->
	<PropertyGroup>
		<PackageId>Orpius.Platform.ClientSdk.ProtobufNet</PackageId>
		<Description>Core library for Orpius operation and tooling integration. This library allows you to integrate your application with the Orpius server; providing communication with, and tools for, your Orpius agents. This library uses Protobuf-net for communications with the Orpius server.</Description>
		<PackageTags>orpius;ai;protobuf;sdk</PackageTags>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

</Project>