<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5fb2e15f-1b2d-43d8-9681-868c8c3aa508</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Orpius.Platform.ClientSdk.ProtobufNet.Generators\Orpius.Platform.ClientSdk.ProtobufNet.Generators.csproj" />
    <ProjectReference Include="..\..\..\..\Orpius.Platform.ClientSdk.ProtobufNet\Orpius.Platform.ClientSdk.ProtobufNet.csproj" />
  </ItemGroup>

</Project>
