<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>11</LangVersion>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".ClientSdk.ProtobufNet",""))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" 
						  PrivateAssets="all"
						  IncludeAssets="compile;build;analyzers;buildtransitive" />
	</ItemGroup>

	<!-- NuGet -->
	<PropertyGroup>
		<PackageId>Orpius.Platform.ClientSdk.ProtobufNet.Generators</PackageId>
		<Description>Source generators that produce the types necessary to register as a tool provider with an Orpius server.</Description>
		<PackageTags>orpius;protobuf;sourcegenerator</PackageTags>

		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<IsPackable>true</IsPackable>
		<PackageIcon>OrpiusLogoIconSquare128.png</PackageIcon>
	</PropertyGroup>

	<!-- Put the built generators in analyzers/dotnet/cs so it's loaded as an analyzer -->
	<ItemGroup>
		<None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
		<None Include="$(OutputPath)$(AssemblyName).pdb" Pack="true" PackagePath="analyzers/dotnet/cs" Condition="Exists('$(OutputPath)$(AssemblyName).pdb')" />
		<None Include="$(OutputPath)$(AssemblyName).xml" Pack="true" PackagePath="analyzers/dotnet/cs" Condition="Exists('$(OutputPath)$(AssemblyName).xml')" />
	</ItemGroup>

</Project>